import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { cancelReconnection, fetchMyReconnections } from '../../services/ReconnectionService';

export default function RevealedScreen() {
  const router = useRouter(); const { sessionId } = useLocalSearchParams(); const [session, setSession] = useState(null);
  useEffect(() => { fetchMyReconnections().then(items => setSession(items.find(item => item.id === sessionId))).catch(() => {}); }, [sessionId]);
  if (!session) return <View style={styles.center}><ActivityIndicator size="large" color="#BE123C" /></View>;
  const partner = session.partner || {}; const name = partner.name || partner.username || 'Your connection';
  const cancel = async () => { try { await cancelReconnection(session.id); router.replace('/home/HomeScreen'); } catch (error) { Alert.alert('Unable to end', error.message); } };
  return <View style={styles.container}><View style={styles.celebrate}><Ionicons name="sparkles" size={42} color="#BE123C" /></View><Text style={styles.eyebrow}>RECONNECTED</Text><Text style={styles.title}>You found each other.</Text><View style={styles.person}><View style={styles.avatar}><Ionicons name="person" size={32} color="#BE123C" /></View><Text style={styles.name}>{name}</Text><Text style={styles.muted}>Your identities are now shared with each other.</Text></View><View style={styles.reward}><Text style={styles.rewardLabel}>YOUR REWARD</Text><Text style={styles.rewardValue}>+{session.base_reward || 0} Connecti Coins</Text><Text style={styles.muted}>Base reward credited by the server</Text></View><TouchableOpacity style={styles.primary} onPress={() => router.push({ pathname: '/home/ChatConversationScreen', params: { friendId: session.participant_a === partner.id ? session.participant_a : session.participant_b, friendName: name } })}><Ionicons name="chatbubble-ellipses" size={20} color="#FFF" /><Text style={styles.primaryText}>Chat with {name}</Text></TouchableOpacity><TouchableOpacity style={styles.ble} onPress={() => router.push({ pathname: '/home/BLETestScreen', params: { sessionId: session.id, partnerId: partner.id } })}><Ionicons name="bluetooth" size={20} color="#BE123C" /><Text style={styles.bleText}>Verify with BLE for 2x eligible reward</Text></TouchableOpacity><TouchableOpacity style={styles.cancel} onPress={cancel}><Text style={styles.cancelText}>Cancel reconnection</Text></TouchableOpacity></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#FFF6F8', padding: 24, paddingTop: 72 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, celebrate: { alignSelf: 'center', width: 84, height: 84, borderRadius: 42, backgroundColor: '#FFE4E6', alignItems: 'center', justifyContent: 'center' }, eyebrow: { textAlign: 'center', color: '#BE123C', fontWeight: '800', letterSpacing: 2, fontSize: 12, marginTop: 22 }, title: { color: '#4C1025', fontSize: 30, fontWeight: '800', textAlign: 'center', marginTop: 10 }, person: { alignItems: 'center', marginTop: 28 }, avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#FFE4E6', alignItems: 'center', justifyContent: 'center' }, name: { color: '#4C1025', fontSize: 22, fontWeight: '800', marginTop: 10 }, muted: { color: '#8D6573', textAlign: 'center', marginTop: 6 }, reward: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 18, marginTop: 24, borderWidth: 1, borderColor: '#FBCFE8' }, rewardLabel: { color: '#8D6573', fontSize: 12, fontWeight: '800', letterSpacing: 1 }, rewardValue: { color: '#BE123C', fontSize: 22, fontWeight: '800', marginTop: 6 }, primary: { flexDirection: 'row', gap: 10, justifyContent: 'center', backgroundColor: '#BE123C', borderRadius: 14, padding: 17, alignItems: 'center', marginTop: 22 }, primaryText: { color: '#FFF', fontWeight: '800', fontSize: 16 }, ble: { flexDirection: 'row', gap: 8, justifyContent: 'center', padding: 17, alignItems: 'center' }, bleText: { color: '#BE123C', fontWeight: '700' }, cancel: { alignItems: 'center', marginTop: 16, padding: 12 }, cancelText: { color: '#9F1239', fontWeight: '800' } });