import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useAuth } from '../../context/AuthProvider';
import { cancelReconnection, continueReconnection, fetchMyReconnections } from '../../services/ReconnectionService';

export default function ShowHintScreen() {
  const router = useRouter(); const { user } = useAuth(); const { sessionId } = useLocalSearchParams(); const [session, setSession] = useState(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  useEffect(() => { (async () => { try { if (sessionId) setSession((await fetchMyReconnections()).find(item => item.id === sessionId)); } catch (error) { Alert.alert('Unavailable', error.message || 'This reconnection is no longer available.'); } finally { setLoading(false); } })(); }, [sessionId]);
  const handleContinue = async () => { if (!session || working) return; setWorking(true); try { const next = await continueReconnection(session.id); router.replace({ pathname: next.phase === 'RECONNECTED' ? '/home/RevealedScreen' : '/home/RevealScreen', params: { sessionId: session.id } }); } catch (error) { Alert.alert('Not available', error.message || 'Please try again.'); } finally { setWorking(false); } };
  const handleIgnore = async () => { if (!session || working) return; setWorking(true); try { await cancelReconnection(session.id); router.replace('/home/HomeScreen'); } catch (error) { Alert.alert('Not available', error.message || 'Please try again.'); } finally { setWorking(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#0F766E" /></View>;
  if (!session) return <View style={styles.center}><Text style={styles.title}>This reconnection is no longer available.</Text></View>;
  const hint = session.hint_payload || {};
  const participantHint = hint.participant_a || {};
  const otherHint = hint.participant_b || {};
  const visibleHint = session.participant_a === user?.id ? otherHint : participantHint;
  return <View style={styles.container}><TouchableOpacity onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color="#173F3A" /></TouchableOpacity><View style={styles.icon}><Ionicons name="eye-off-outline" size={42} color="#0F766E" /></View><Text style={styles.eyebrow}>SHOW HINTS</Text><Text style={styles.title}>Someone you know might be nearby.</Text><Text style={styles.body}>{hint.shared_context || 'A friend is also open to reconnecting in this Connecti Zone.'}</Text><View style={styles.hintCard}><Ionicons name="person-outline" size={22} color="#0F766E" /><View style={styles.hintCopy}><Text style={styles.hintText}>Username starts with {visibleHint.username_initial || 'C'}</Text><Text style={styles.hintDetail}>{visibleHint.birth_year ? `Born in ${visibleHint.birth_year}` : 'Someone from your Connecti circle'}</Text>{visibleHint.bio ? <Text style={styles.hintDetail}>{visibleHint.bio}</Text> : null}</View></View><Text style={styles.privacy}>No exact location, distance, or private contact details are shared before mutual reveal.</Text><TouchableOpacity style={styles.primary} onPress={handleContinue} disabled={working}><Text style={styles.primaryText}>{working ? 'Checking...' : 'Reveal'}</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={handleIgnore} disabled={working}><Text style={styles.secondaryText}>Ignore</Text></TouchableOpacity></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F4FBF8', padding: 24, paddingTop: 60 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F4FBF8' }, icon: { alignSelf: 'center', width: 104, height: 104, borderRadius: 52, backgroundColor: '#D9F4EA', alignItems: 'center', justifyContent: 'center', marginTop: 58, marginBottom: 28 }, eyebrow: { textAlign: 'center', color: '#0F766E', fontWeight: '800', letterSpacing: 2, fontSize: 12 }, title: { color: '#173F3A', fontSize: 32, lineHeight: 38, fontWeight: '800', textAlign: 'center', marginTop: 14 }, body: { color: '#52706A', fontSize: 16, lineHeight: 24, textAlign: 'center', marginTop: 16 }, hintCard: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', backgroundColor: '#FFF8E7', padding: 18, borderRadius: 14, marginTop: 28 }, hintCopy: { flex: 1, gap: 5 }, hintText: { color: '#7C4A03', fontWeight: '700' }, hintDetail: { color: '#8A6A32', lineHeight: 19 }, privacy: { color: '#6B827C', textAlign: 'center', fontSize: 13, lineHeight: 19, marginTop: 22 }, primary: { backgroundColor: '#0F766E', borderRadius: 14, padding: 17, alignItems: 'center', marginTop: 32 }, primaryText: { color: '#FFF', fontWeight: '800', fontSize: 16 }, secondary: { alignItems: 'center', padding: 18 }, secondaryText: { color: '#52706A', fontWeight: '700' } });
